// DO NOT EDIT THIS FILE
// This file is generated automatically by the typed-scss-modules library
export type Styles = {
  description: string;
  iconPhoto: string;
  linkIcons: string;
  microText: string;
  text: string;
  title: string;
  wrap: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
