// DO NOT EDIT THIS FILE
// This file is generated automatically by the typed-scss-modules library
export type Styles = {
  button: string
  error: string
  info: string
  primary: string
  success: string
  warning: string
}

export type ClassNames = keyof Styles

declare const styles: Styles

export default styles
