// DO NOT EDIT THIS FILE
// This file is generated automatically by the typed-scss-modules library
export type Styles = {
  inde: string
  logo: string
  menuPc: string
  menuPcItem: string
  menuSp: string
  menuSpDrawer: string
  menuSpItem: string
  menuSpLarge: string
  open: string
  wrap: string
}

export type ClassNames = keyof Styles

declare const styles: Styles

export default styles
