// DO NOT EDIT THIS FILE
// This file is generated automatically by the typed-scss-modules library
export type Styles = {
  link: string
  workItem: string
  workItemImg: string
  workItemTitle: string
  worksList: string
  worksTitle: string
  wrap: string
}

export type ClassNames = keyof Styles

declare const styles: Styles

export default styles
