name: Run Danger
on: [pull_request]

jobs:
  build:
    name: Run Danger
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Danger
        uses: danger/danger-js@11.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
